name: device_explorer
description: "Device Xplore | Android File Transfer for macOS"


publish_to: 'none' 

version: 2.0.0+3

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  path_provider: ^2.1.3
  chewie: ^1.8.1
  pdf_render: 1.3.8
  flutter_archive: 6.0.0
  just_audio: ^0.9.38
  flutter_svg: ^2.0.10+1
  dio: ^5.4.3+1
  package_info_plus: ^8.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/
    - assets/audios/

flutter_launcher_icons:
  android: false
  ios: false
  macos:
    generate: true
    image_path: "assets/logo/device-xplore.png"
