name: device_explorer
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  path_provider: ^2.1.3
  filesystem_picker: ^4.1.0
  chewie: ^1.8.1
  pdf_render: 1.3.8
  flutter_archive: 6.0.0
  archive: ^3.6.0
  just_audio: ^0.9.38


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/
    - assets/audios/

flutter_launcher_icons:
  android: false
  ios: false
  macos:
    generate: true
    image_path: "assets/logo/device-xplore.png"
