import 'package:device_explorer/src/common/translate/lang_key.dart';

Map<String, String> en = {
  LangKey.back: 'Back',
  LangKey.storageSetting: 'Storage',
  LangKey.fileSetting: 'File Setting',
  LangKey.setting: 'Settings',
  LangKey.home: 'Home',
  LangKey.newFolder: 'New Folder (⌘ + N)',
  LangKey.rename: 'Edit Name (⌘ + D)',
  LangKey.delete: 'Delete (Backspace)',
  LangKey.copy: 'Copy (⌘ + C)',
  LangKey.paste: 'Paste (⌘ + V)',
  LangKey.sort: 'Sort',
  LangKey.reload: 'Reload file (⌘ + R)',
  LangKey.addTab: 'New tab',
  LangKey.name: 'Name',
  LangKey.length: 'Length',
  LangKey.type: 'Type',
  LangKey.size: 'Size',
  LangKey.modified: 'Modified',
  LangKey.nameA2Z: 'Name A to Z',
  LangKey.nameZ2A: 'Name Z to A',
  LangKey.sortType: 'By Type',
  LangKey.dateA2Z: 'Date increment',
  LangKey.dateZ2A: 'Date decrement',
  LangKey.lengthA2Z: 'By length increment',
  LangKey.lengthZ2A: 'By length decrement',
  LangKey.ok: 'OK',
  LangKey.cancel: 'Cancel',
  LangKey.newFolderTitle: 'Folder name',
  LangKey.newFileName: 'File name',
  LangKey.confirmDelete: 'Are you want to delete file/files?',
};
