import 'package:device_explorer/src/common/translate/lang_key.dart';

Map<String, String> vi = {
  LangKey.back: 'Quay lại',
  LangKey.storageSetting: 'Bộ nhớ',
  LangKey.fileSetting: 'Danh sách tệp',
  LangKey.setting: 'Cài đặt',
  LangKey.home: 'Trang chủ',
  LangKey.newFolder: 'Thư mục mới (⌘ + N)',
  LangKey.rename: 'Đổi tên (⌘ + D)',
  LangKey.delete: 'Xoá (Backspace)',
  LangKey.copy: 'Sao chép (⌘ + C)',
  LangKey.paste: 'Dán (⌘ + V)',
  LangKey.sort: 'Sắp xếp',
  LangKey.reload: 'Làm mới (⌘ + R)',
  LangKey.addTab: 'Thẻ mới',
  LangKey.name: 'Tên',
  LangKey.length: 'Dung lượng',
  LangKey.type: 'Loại',
  LangKey.size: 'Tệp con',
  LangKey.modified: 'Thời gian sửa',
  LangKey.nameA2Z: 'Tên A đến Z',
  LangKey.nameZ2A: 'Tên Z đến A',
  LangKey.sortType: 'Bởi phân loại',
  LangKey.dateA2Z: 'Thời gian tăng dần',
  LangKey.dateZ2A: 'Thời gian giảm dần',
  LangKey.lengthA2Z: 'Dung lượng tăng dần',
  LangKey.lengthZ2A: 'Dung lượng giảm dần',
  LangKey.ok: 'Đồng ý',
  LangKey.cancel: 'Huỷ bỏ',
  LangKey.newFolderTitle: 'Tên thư mục',
  LangKey.newFileName: 'Tên tệp',
  LangKey.confirmDelete: 'Bạn có chắc chắn muốn xoá thư mục/tệp này?',
  LangKey.languageSetting: 'Ngôn ngữ',
};
